# Generated by Django 2.2.6 on 2021-10-02 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomreservation',
            old_name='room',
            new_name='room_id',
        ),
        migrations.AlterUniqueTogether(
            name='roomreservation',
            unique_together={('room_id', 'date')},
        ),
    ]
